package net.techest.ug.mvc.entity;
// Generated Sep 15, 2011 3:56:31 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colleague generated by hbm2java
 */
@Entity
@Table(name = "colleague", catalog = "uggradution")
public class Colleague implements java.io.Serializable {

    private Integer id;
    private String name;
    private int statu;

    @Override
    public String toString() {
        return "ID:" + id + " 名字:" + name + " 状态:" + statu;
    }

    public Colleague() {
    }

    public Colleague(String name, int statu) {
        this.name = name;
        this.statu = statu;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "statu", nullable = false)
    public int getStatu() {
        return this.statu;
    }

    public void setStatu(int statu) {
        this.statu = statu;
    }
}
