package net.techest.ug.mvc.entity;
// Generated Sep 26, 2011 9:19:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paperyear generated by hbm2java
 */
@Entity
@Table(name="paperyear"
    ,catalog="uggradution"
)
public class Paperyear  implements java.io.Serializable {


     private int id;
     private int mid;
     private int maxsel;

     private Date dtstart;
     private Date dtend;
     private int statu;

    public Paperyear() {
    }

    public int getMaxsel() {
        return maxsel;
    }

    public void setMaxsel(int maxsel) {
        this.maxsel = maxsel;
    }

    public Paperyear(int id, Date dtstart, Date dtend, int statu) {
       this.id = id;
       this.dtstart = dtstart;
       this.dtend = dtend;
       this.statu = statu;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dtstart", nullable=false, length=0)
    public Date getDtstart() {
        return this.dtstart;
    }
    
    public void setDtstart(Date dtstart) {
        this.dtstart = dtstart;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dtend", nullable=false, length=0)
    public Date getDtend() {
        return this.dtend;
    }
    
    public void setDtend(Date dtend) {
        this.dtend = dtend;
    }
    
    @Column(name="statu", nullable=false)
    public int getStatu() {
        return this.statu;
    }
    
    public void setStatu(int statu) {
        this.statu = statu;
    }


    public int getMid() {
        return mid;
    }

    public void setMid(int mid) {
        this.mid = mid;
    }


}


