package net.techest.ug.mvc.entity;
// Generated Sep 15, 2011 3:56:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="permission"
    ,catalog="uggradution"
)
public class Permission  implements java.io.Serializable {


     private Integer id;
     private String desp;
     private String key;
     private int statu;

    public Permission() {
    }

    public Permission(String desp, String key, int statu) {
       this.desp = desp;
       this.key = key;
       this.statu = statu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="desp", nullable=false, length=300)
    public String getDesp() {
        return this.desp;
    }
    
    public void setDesp(String desp) {
        this.desp = desp;
    }
    
    @Column(name="key", nullable=false, length=300)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    
    @Column(name="statu", nullable=false)
    public int getStatu() {
        return this.statu;
    }
    
    public void setStatu(int statu) {
        this.statu = statu;
    }




}


