package net.techest.ug.mvc.entity;
// Generated Sep 15, 2011 3:56:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Selection generated by hbm2java
 */
@Entity
@Table(name="selection"
    ,catalog="uggradution"
)
public class Selection  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private int sid;
     private int statu;

    public Selection() {
    }

    public Selection(int uid, int sid, int statu) {
       this.uid = uid;
       this.sid = sid;
       this.statu = statu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    
    @Column(name="sid", nullable=false)
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    
    @Column(name="statu", nullable=false)
    public int getStatu() {
        return this.statu;
    }
    
    public void setStatu(int statu) {
        this.statu = statu;
    }




}


