package net.techest.ug.mvc.entity;
// Generated Sep 15, 2011 3:56:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userfields generated by hbm2java
 */
@Entity
@Table(name="userfields"
    ,catalog="uggradution"
)
public class Userfields  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private String name;
     private String text;
     private String tel;
     private String email;
     private Date regtime;
     private String regip;
     private Date lastlogintime;
     private String lastloginip;
     private int maxpapers;
     private int type;

    public Userfields() {
        this.name="";
        this.tel="";
        this.email="";
        this.text="";
        this.type=0;
    }

	
    public Userfields(int uid, String name, String text, String tel, String email, Date regtime, String regip, Date lastlogintime, String lastloginip, int type) {
       this.uid = uid;
       this.name = name;
       this.text = text;
       this.tel = tel;
       this.email = email;
       this.regtime = regtime;
       this.regip = regip;
       this.lastlogintime = lastlogintime;
       this.lastloginip = lastloginip;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    @Column(name="tel", length=32)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="email", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="regtime", nullable=false, length=0)
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    
    @Column(name="regip", nullable=false, length=32)
    public String getRegip() {
        return this.regip;
    }
    
    public void setRegip(String regip) {
        this.regip = regip;
    }
    public void setMaxpapers(Integer maxpapers) {
        this.maxpapers = maxpapers;
    }
    
    @Column(name="maxpapers")
    public int getMaxpapers() {
        return this.maxpapers;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastlogintime", nullable=false, length=0)
    public Date getLastlogintime() {
        return this.lastlogintime;
    }
    
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }
    
    @Column(name="lastloginip", nullable=false, length=32)
    public String getLastloginip() {
        return this.lastloginip;
    }
    
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip;
    }
    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }




}


