package net.techest.ug.mvc.entity;
// Generated Sep 15, 2011 3:56:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="uggradution"
    , uniqueConstraints = @UniqueConstraint(columnNames="sid") 
)
public class User  implements java.io.Serializable {


     private Integer id;
     private int gid;
     private String sid;
     private int mid;
     private String permissionset;
     private String username;
     private String password;
     private int type;
     private int statu;

    public User() {
        this.permissionset="";
        this.sid="";
        this.username="";
    }

    public User(int gid, String sid, int mid, String permissionset, String username, String password, int type, int statu) {
       this.gid = gid;
       this.sid = sid;
       this.mid = mid;
       this.permissionset = permissionset;
       this.username = username;
       this.password = password;
       this.type = type;
       this.statu = statu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="gid", nullable=false)
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }
    
    @Column(name="sid", unique=true, nullable=false, length=32)
    public String getSid() {
        return this.sid;
    }
    
    public void setSid(String sid) {
        this.sid = sid;
    }
    
    @Column(name="mid", nullable=false)
    public int getMid() {
        return this.mid;
    }
    
    public void setMid(int mid) {
        this.mid = mid;
    }
    
    @Column(name="permissionset", nullable=false, length=65535)
    public String getPermissionset() {
        return this.permissionset;
    }
    
    public void setPermissionset(String permissionset) {
        this.permissionset = permissionset;
    }
    
    @Column(name="username", nullable=false, length=16)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false, length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    
    @Column(name="statu", nullable=false)
    public int getStatu() {
        return this.statu;
    }
    
    public void setStatu(int statu) {
        this.statu = statu;
    }




}


