package net.techest.ug.mvc.entity;
// Generated Sep 20, 2011 9:19:09 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name="usergroup"
    ,catalog="uggradution"
)
public class Usergroup  implements java.io.Serializable {


     private Integer id;
     private String permissionset;
     private String desp;
     private String home;
     private int statu;

    public Usergroup() {
    }

    public Usergroup(String permissionset, String desp, String home, int statu) {
       this.permissionset = permissionset;
       this.desp = desp;
       this.home = home;
       this.statu = statu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="permissionset", nullable=false, length=65535)
    public String getPermissionset() {
        return this.permissionset;
    }
    
    public void setPermissionset(String permissionset) {
        this.permissionset = permissionset;
    }
    
    @Column(name="desp", nullable=false, length=300)
    public String getDesp() {
        return this.desp;
    }
    
    public void setDesp(String desp) {
        this.desp = desp;
    }
    
    @Column(name="home", nullable=false, length=50)
    public String getHome() {
        return this.home;
    }
    
    public void setHome(String home) {
        this.home = home;
    }
    
    @Column(name="statu", nullable=false)
    public int getStatu() {
        return this.statu;
    }
    
    public void setStatu(int statu) {
        this.statu = statu;
    }




}


